
<div class="jumbotron layui-row">
        <div class="layui-col-xs12" style="margin: 20px 0;"><img alt="" src="/statics/img/banner.jpg" width="100%"></div>
    </div>
<div class="c-body layui-col-md12">
    <div class="body-content">

        <div class="layui-row">
            <div class="layui-col-md8">
                <div class="layui-fluid layadmin-cmdlist-fluid">
  <div class="layui-row layui-col-space30">
    <?php if(!empty($wxGroup)):foreach ($wxGroup as $val):?>
    <div class="layui-col-md3">
        <div class="cmdlist-container" style="text-align:center">
            <a href="<?=$this->url->get('wx/detail', ['id'=>$val['id']])?>" target="_blank"><img src="<?=$val['code']?>" with="110" height="110"></a>
            <a href="<?=$this->url->get('wx/detail', ['id'=>$val['id']])?>" target="_blank">
              <div class="cmdlist-text">
                <p class="info" style="height: 30px;line-height:30px;text-align:center;"><?=$val['name']?></p>
              </div>
            </a>
        </div>
    </div>
    <?php endforeach;endif;?>
  </div>
</div>
            </div>
            <div class="layui-col-md4 sidebar ">
                <div class="widget">
                	<h4 class="title">分类</h4>
                	<div class="content tag-cloud">
                		<?php foreach ($category as $val):?>
                		<a href="<?=$this->url->get('wx/list', ['category'=>$val['id']])?>"><?=$val['name']?></a>
                		<?php endforeach;?>
                	</div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
$(function(){
	$('#myTabs a').click(function (e) {
	  e.preventDefault()
	  $(this).tab('show')
	})
	$('#myTabs a[href="#profile"]').tab('show') // Select tab by name
	$('#myTabs a:first').tab('show') // Select first tab
	$('#myTabs a:last').tab('show') // Select last tab
	$('#myTabs li:eq(2) a').tab('show') // Select third tab (0-indexed)
});
</script>