<div class="site-index">
        
    <div class="jumbotron">
        <div style="background: #000;height:200px"></div>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                	<div class="col-lg-12">
                		<div class="bs-example bs-example-tabs" data-example-id="togglable-tabs">
                            <ul id="myTabs" class="nav nav-tabs" role="tablist">
                              <li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Home</a></li>
                              <li role="presentation" class=""><a href="#profile" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile" aria-expanded="false">Profile</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                              <div role="tabpanel" class="tab-pane fade active in" id="home" aria-labelledby="home-tab">
                                <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
                              </div>
                              <div role="tabpanel" class="tab-pane fade" id="profile" aria-labelledby="profile-tab">
                                <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.</p>
                              </div>
                            </div>
                          </div>
                	</div>
                </div>
            </div>
            <div class="col-lg-4 sidebar ">
                <div class="widget">
                	<h4 class="title">标签云</h4>
                	<div class="content tag-cloud">
                		<a href="/tag/ke-hu-duan/">客户端</a>
                        <a href="/tag/android/">Android</a>
                        <a href="/tag/jquery/">jQuery</a>
                        <a href="/tag/ghost-0-7-ban-ben/">Ghost 0.7 版本</a>
                        <a href="/tag/opensource/">开源</a>
                        <a href="/tag/zhu-shou-han-shu/">助手函数</a>
                        <a href="/tag/tag-cloud/">标签云</a>
                        <a href="/tag/navigation/">导航</a>
                        <a href="/tag/customize-page/">自定义页面</a>
                        <a href="/tag/static-page/">静态页面</a>
                        <a href="/tag/roon-io/">Roon.io</a>
                        <a href="/tag/configuration/">配置文件</a>
                        <a href="/tag/upyun/">又拍云存储</a>
                        <a href="/tag/upload/">上传</a>
                        <a href="/tag/handlebars/">Handlebars</a>
                        <a href="/tag/email/">邮件</a>
                        <a href="/tag/shortcut/">快捷键</a>
                        <a href="/tag/yong-hu-zhi-nan/">用户指南</a>
                	</div>
                </div>
            </div>
        </div>
        
        <div class="row">
        	<div class="col-lg-12">
        		<div class="bs-example bs-example-tabs" data-example-id="togglable-tabs">
                    <ul id="myTabs" class="nav nav-tabs" role="tablist">
                      <li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Home</a></li>
                      <li role="presentation" class=""><a href="#profile" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile" aria-expanded="false">Profile</a></li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                      <div role="tabpanel" class="tab-pane fade active in topic-list" id="home" aria-labelledby="home-tab">
                        <div class="topic-item col-lg-6">
                            <div class="author-avatar">
                                <a href="/member/index/1" style="color: #333;"><img src="http://img.itdocs.org/2018072710545018034.jpg?imageView2/1/w/150/h/150/q/75|imageslim"></a>
                                <div style="margin: 20px 0 10px;"><a href="/member/index/1" style="color: #333;">ITer</a></div>
        <!--                        <span class="manager">管理员</span>-->
                            </div>
                            <div class="topic-content">
                                <span class="arrow"></span>
                                                            <span class="tag red border-red">置顶</span>
                                                        <span class="tag green border-green">讨论</span>
                                <div class="title">
                                    <a href="/topic/detail/118" title="如何用 Yii2 快速打造个人博客系统">如何用 Yii2 快速打造个人博客系统</a>
                                </div>
                                <div class="content">
                                    说明
        
        
        课程简介
        素材及源码
        纠错
        
        
        课程简介
        
        本课程主要内容是如何通过使用 yii2 框架，快速打造个人博客系统。
        
        博客系统主要分两个部分：
        
        
        后台管理系统（backend）
        相关内容：yii2-admin扩展， RBAC基于角色的权限管理，基于Markdown的富文本编辑器，上传图片到七牛，Gii生成代码，自定义Gii模版
        
        前台内容展示（frontend）
        相关内容：挂件的应用（widget），博客首页界面排版，文章内容呈现，博客时间史
        
        
        
        素材及源码
        
        为了方便大家学习 yii2 相关的知识并应用于实践中，本次教程会提供学习素材。什么是素材呢？就是基于 hyii2 后台管理系统添加了学习教程时所需要的样式文件，js文件，界面排版等。让大家免去在学习后端框架的过程中，去写前端的页面和js。更加精确的掌握 yii2 框架的实战应用。通过教程的学习可以开发出相应的一套完整的博客系统。详情查看 应用搭建 一章
        
        
          为了保证课程的高品质，我们需要对素材进行收费，购买链接。购买后请联系 391430388 获取素材和源码
        
        
        
        前台界面预览：http://hyblog.itdocs.org
        管理后台地址：http://hyblog-admin.itdocs.org
        账户：test 密码：123456
        
        
        
          作者会提供完整的开发素材和成品源码，希望不要借此传播，尊重原创，万分感谢。
        
        
        纠错
        
        教程中遇到的问题，可以先自己尝试解决，培养自身的问题排查能力是一个程序员基本的要求。
        
        
        本地环境问题（本站统一环境教程：PHP开发环境部署）。
        代码书写错误，引起的报错。
        搜索本教程错误集锦（开发中）
        
        
        若仍不能解决，请联系 QQ：391430388
        
        当然人无完人，也许教程中也存在一些不可避免的疏漏，如果发现可以联系作者，先行致谢！
                                </div>
        
                                                        <span class="is-fine pull-left"><i class="fa fa-trophy"></i>精华贴</span>
                                                        <div class="extra pull-right">
                                    <span style="margin-right: 15px"><i class="fa fa-clock-o" style="font-size: 14px;"></i>11天前</span>
                                    <span><i class="fa fa-heart"></i>喜欢（1）</span>
                                    <span><i class="fa fa-eye"></i>浏览（276）</span>
                                    <span><i class="fa fa-commenting"></i>评论（1）</span>
                                </div>
                            </div>
                        </div>
                        <div class="topic-item  col-lg-6">
                            <div class="author-avatar">
                                <a href="/member/index/1" style="color: #333;"><img src="http://img.itdocs.org/2018072710545018034.jpg?imageView2/1/w/150/h/150/q/75|imageslim"></a>
                                <div style="margin: 20px 0 10px;"><a href="/member/index/1" style="color: #333;">ITer</a></div>
        <!--                        <span class="manager">管理员</span>-->
                            </div>
                            <div class="topic-content">
                                <span class="arrow"></span>
                                                            <span class="tag red border-red">置顶</span>
                                                        <span class="tag green border-green">讨论</span>
                                <div class="title">
                                    <a href="/topic/detail/118" title="如何用 Yii2 快速打造个人博客系统">如何用 Yii2 快速打造个人博客系统</a>
                                </div>
                                <div class="content">
                                    说明
        
        
        课程简介
        素材及源码
        纠错
        
        
        课程简介
        
        本课程主要内容是如何通过使用 yii2 框架，快速打造个人博客系统。
        
        博客系统主要分两个部分：
        
        
        后台管理系统（backend）
        相关内容：yii2-admin扩展， RBAC基于角色的权限管理，基于Markdown的富文本编辑器，上传图片到七牛，Gii生成代码，自定义Gii模版
        
        前台内容展示（frontend）
        相关内容：挂件的应用（widget），博客首页界面排版，文章内容呈现，博客时间史
        
        
        
        素材及源码
        
        为了方便大家学习 yii2 相关的知识并应用于实践中，本次教程会提供学习素材。什么是素材呢？就是基于 hyii2 后台管理系统添加了学习教程时所需要的样式文件，js文件，界面排版等。让大家免去在学习后端框架的过程中，去写前端的页面和js。更加精确的掌握 yii2 框架的实战应用。通过教程的学习可以开发出相应的一套完整的博客系统。详情查看 应用搭建 一章
        
        
          为了保证课程的高品质，我们需要对素材进行收费，购买链接。购买后请联系 391430388 获取素材和源码
        
        
        
        前台界面预览：http://hyblog.itdocs.org
        管理后台地址：http://hyblog-admin.itdocs.org
        账户：test 密码：123456
        
        
        
          作者会提供完整的开发素材和成品源码，希望不要借此传播，尊重原创，万分感谢。
        
        
        纠错
        
        教程中遇到的问题，可以先自己尝试解决，培养自身的问题排查能力是一个程序员基本的要求。
        
        
        本地环境问题（本站统一环境教程：PHP开发环境部署）。
        代码书写错误，引起的报错。
        搜索本教程错误集锦（开发中）
        
        
        若仍不能解决，请联系 QQ：391430388
        
        当然人无完人，也许教程中也存在一些不可避免的疏漏，如果发现可以联系作者，先行致谢！
                                </div>
        
                                                        <span class="is-fine pull-left"><i class="fa fa-trophy"></i>精华贴</span>
                                                        <div class="extra pull-right">
                                    <span style="margin-right: 15px"><i class="fa fa-clock-o" style="font-size: 14px;"></i>11天前</span>
                                    <span><i class="fa fa-heart"></i>喜欢（1）</span>
                                    <span><i class="fa fa-eye"></i>浏览（276）</span>
                                    <span><i class="fa fa-commenting"></i>评论（1）</span>
                                </div>
                            </div>
                        </div>
                      </div>
                      <div role="tabpanel" class="tab-pane fade" id="profile" aria-labelledby="profile-tab">
                        <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.</p>
                      </div>
                    </div>
                  </div>
        	</div>
        </div>
    </div>
</div>
<script>
$(function(){
	$('#myTabs a').click(function (e) {
	  e.preventDefault()
	  $(this).tab('show')
	})
	$('#myTabs a[href="#profile"]').tab('show') // Select tab by name
	$('#myTabs a:first').tab('show') // Select first tab
	$('#myTabs a:last').tab('show') // Select last tab
	$('#myTabs li:eq(2) a').tab('show') // Select third tab (0-indexed)
});
</script>