<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Insert title hereaa</title>
<link href="/statics/plugins/bootstrap/css/bootstrap.css"
	rel="stylesheet">
<link href="/statics/css/site.css" rel="stylesheet">
<script src="/statics/js/jquery.min.js"></script>
</head>
<body>
	<div class="wrap">
		<nav id="w0" class="navbar-inverse navbar-fixed-top navbar">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse"
						data-target="#w0-collapse">
						<span class="sr-only">Toggle navigation</span> <span
							class="icon-bar"></span> <span class="icon-bar"></span> <span
							class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/index.php">My Application</a>
				</div>
				<div id="w0-collapse" class="collapse navbar-collapse">
					<ul id="w1" class="navbar-nav navbar-right nav">
						<li class="active"><a href="/index.php?r=site%2Findex">Home</a></li>
						<li><a href="<?=$this->url->get('wx/list');?>">列表</a></li>
						<li><a href="/index.php?r=site%2Fcontact">Contact</a></li>
						<li><a href="<?=$this->url->get('login/register');?>">注册</a></li>
						<li><a href="<?=$this->url->get('login/index');?>">登录</a></li>
					</ul>
				</div>
			</div>
		</nav>
		<div class="container">
            <?php echo $this->getContent(); ?>
        </div>
	</div>

	<footer class="footer">
		<div class="container">
			<p class="pull-left">&copy; My Application 2018</p>

			<p class="pull-right">
				Powered by <a href="http://www.yiiframework.com/" rel="external">Yii
					Framework</a>
			</p>
		</div>
	</footer>

	<script src="/statics/plugins/bootstrap/js/bootstrap.js"></script>
</body>
</htm>