<div class="layui-col-md12" style="height:40px;line-height:40px;">
    <span class="layui-breadcrumb" style="visibility: visible;">
      <a>位置：</a>
      <a href="/">首页</a>
      <span lay-separator="">/</span>
      <a>注册</a>
      <span lay-separator="">/</span>
      <a><cite>激活</cite></a>
    </span>
</div>
<div class="c-body layui-col-md12">
	<div style="margin: 50px 10px;line-height:30px;">
		<p class="red"><?=$msg?></p>
	</div>
</div>
