<div class="site-wxlist">
	<div class="row screen">
		<div class="col-lg-12">
			<div class="row">
				<div class="col-lg-1 title">类型：</div>
				<div class="col-lg-11 tag"><a>123</a><a>阿斯顿发顺丰</a><a>asdfsd</a><a>阿撒旦法的萨芬</a><a>斯蒂芬斯蒂芬但是</a><a>斯蒂芬的是</a><a>双方的但是</a><a>123</a><a>撒旦发射点</a><a>阿斯蒂芬岁的</a><a>斯蒂芬的是</a><a>123</a><a>日突然</a><a>栅格化柔荑花</a><a>是发放</a><a>123</a><a>123</a><a>123</a></div>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-lg-12 list">
			<div class="group">
				<div class="lead-img"><img alt="context" src="/statics/img/1.jpg" width="170" height="170"></div>
				<div class="group-title">adminadmin</div>
				<div class="group-desc">jianjiejanjiejianjiejanjiejianjiejanjiejianjiejanjiejianjiejanjiejianjiejanjiejianjiejanjie</div>
				<div class="group-time"><span class="pull-left">1天前</span><span class="pull-right">3221</span></div>
			</div>
			<div class="group">
				<div class="lead-img"><img alt="context" src="/statics/img/1.jpg" width="170" height="170"></div>
				<div class="group-title">adminadmin</div>
				<div class="group-desc">jianjiejanjie</div>
				<div class="group-time"><span class="pull-left">1天前</span><span class="pull-right">3221</span></div>
			</div>
			<div class="group">
				<div class="lead-img"><img alt="context" src="/statics/img/1.jpg" width="170" height="170"></div>
				<div class="group-title">adminadmin</div>
				<div class="group-desc">jianjiejanjie</div>
				<div class="group-time"><span class="pull-left">1天前</span><span class="pull-right">3221</span></div>
			</div>
			<div class="group">
				<div class="lead-img"><img alt="context" src="/statics/img/1.jpg" width="170" height="170"></div>
				<div class="group-title">adminadmin</div>
				<div class="group-desc">jianjiejanjie</div>
				<div class="group-time"><span class="pull-left">1天前</span><span class="pull-right">3221</span></div>
			</div>
			<div class="group">
				<div class="lead-img"><img alt="context" src="/statics/img/1.jpg" width="170" height="170"></div>
				<div class="group-title">adminadmin</div>
				<div class="group-desc">jianjiejanjie</div>
				<div class="group-time"><span class="pull-left">1天前</span><span class="pull-right">3221</span></div>
			</div>
			<div class="group">
				<div class="lead-img"><img alt="context" src="/statics/img/1.jpg" width="170" height="170"></div>
				<div class="group-title">adminadmin</div>
				<div class="group-desc">jianjiejanjie</div>
				<div class="group-time"><span class="pull-left">1天前</span><span class="pull-right">3221</span></div>
			</div>
			<div class="group">
				<div class="lead-img"><img alt="context" src="/statics/img/1.jpg" width="170" height="170"></div>
				<div class="group-title">adminadmin</div>
				<div class="group-desc">jianjiejanjie</div>
				<div class="group-time"><span class="pull-left">1天前</span><span class="pull-right">3221</span></div>
			</div>
		</div>
		<div class="col-lg-12 page"><a>首页</a><a>上下一页</a><span>1/2</span><a>下一页</a><a>尾页</a></div>
	</div>
</div>