<div class="layui-col-md12" style="height:40px;line-height:40px;">
    <span class="layui-breadcrumb" style="visibility: visible;">
      <a>位置：</a>
      <a href="/">首页</a>
      <span lay-separator="">/</span>
      <a>微信群</a>
      <span lay-separator="">/</span>
      <a><cite>列表</cite></a>
    </span>
</div>
<div class="c-body layui-col-md12">
	<div class="layui-row screen sx">
		<div class="layui-col-lg12">
			<div class="layui-row">
				<div class="layui-col-md1 title">类型：</div>
				<div class="layui-col-md11 tag">
					<a href="<?php if(empty($categoryId)):echo 'javascript:;';else :$this->url->get('wx/list');endif;?>" class="<?php if(empty($categoryId))echo 'active';?>">全部</a>
					<?php foreach ($category as $val) :?>
						<a href="<?php if($val['id'] != $categoryId):echo $this->url->get('wx/list', ['categoryId'=>$val['id']]);else :echo 'javascript:;';endif;?>" class="<?php if($val['id'] == $categoryId)echo 'active';?>"><?=$val['name']?></a>
					<?php endforeach;?>
				</div>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-lg-12 list">
			<div class="layui-fluid layadmin-cmdlist-fluid">
  <div class="layui-row layui-col-space30">
    <?php if(!empty($wxGroup['list'])):foreach ($wxGroup['list'] as $val):?>
    <div class="layui-col-md2 layui-col-sm4">
        <div class="cmdlist-container" style="text-align:center">
            <a href="<?=$this->url->get('wx/detail', ['id'=>$val['id']])?>" target="_blank"><img src="<?=$val['code']?>" with="110" height="110"></a>
            <a href="<?=$this->url->get('wx/detail', ['id'=>$val['id']])?>" target="_blank">
              <div class="cmdlist-text">
                <p class="info" style="height: 30px;line-height:30px;text-align:center;"><?=$val['name']?></p>
                <div class="price">
                    <p><?=date('H:i', strtotime($val['update_time']))?></p>
                    <span class="flow"> 查看：433</span>
                </div>
              </div>
            </a>
        </div>
    </div>
    <?php endforeach;endif;?>
    <div class="layui-col-md12 layui-col-sm12">
        <div id="page"></div>
    </div>
  </div>
</div>
		</div>
	</div>
</div>
<script>
$(function(){
	layui.use('laypage', function(){
		  var laypage = layui.laypage;
		  
		  //执行一个laypage实例
		  laypage.render({
		    elem: 'page' //注意，这里的 test1 是 ID，不用加 # 号
		    ,count: <?=$wxGroup['pageinfo']['total']?>, //数据总数，从服务端得到
		  limit:24,
		  });
		});
});
</script>