<div class="layui-col-md12" style="height:40px;line-height:40px;">
    <span class="layui-breadcrumb" style="visibility: visible;">
      <a>位置：</a>
      <a href="/">首页</a>
      <span lay-separator="">/</span>
      <a>注册</a>
      <span lay-separator="">/</span>
      <a><cite>忘记密码</cite></a>
    </span>
</div>
<div class="c-body layui-col-md12">
	<div class="layui-row">
	<div class="layui-card-header">找回密码</div>
	<div class="layui-card-body layui-row layui-col-space10">
		<?php if($type == 2):?>
		<div style="margin: 50px 10px;line-height:30px;">
    		<p class="red"><?=$msg?></p>
    	</div>
		<?php else :?>
		<form class="layui-form" action="<?=$this->url->get('login/resetPassword', ['type'=>2, 'token'=>$token]);?>" method="post">
          <div class="layui-form-item">
            <label class="layui-form-label">新密码</label>
            <div class="layui-input-inline">
              <input type="password" name="password" id="password" required lay-verify="required|pass" placeholder="不能小于6个字" autocomplete="off" class="layui-input">
            </div>
          </div>
          <div class="layui-form-item">
            <label class="layui-form-label">确认密码</label>
            <div class="layui-input-inline">
              <input type="password" name="rpassword" id="rpassword" required lay-verify="required|pass|tong" placeholder="不能小于6个字" autocomplete="off" class="layui-input">
            </div>
          </div>
          <div class="layui-form-item">
            <div class="layui-input-block">
              <button class="layui-btn" lay-submit lay-filter="formDemo">提交</button>
            </div>
          </div>
        </form>
        <?php endif;?>
	</div>
</div>
</div>
<script>
$(function(){
	layui.use('form', function(){
		var form = layui.form;
		  
		  //监听提交
		  form.on('submit(formDemo)', function(data){
	     });

		  form.verify({
			  tong: function(value, item){ //value：表单的值、item：表单的DOM对象
				if($('#password').val() != value){
					return '两次密码不一致';
				}
			  }
			  
			  //我们既支持上述函数式的方式，也支持下述数组的形式
			  //数组的两个值分别代表：[正则匹配、匹配不符时的提示文字]
			  ,pass: [
			    /^[\S]{6,12}$/
			    ,'密码必须6到12位，且不能出现空格'
			  ] 
			});  
	});
});
</script>