<div class="site-wxdetail">
	<div class="row">
		<div class="col-lg-9">
    		<div class="row">
        		<div class="col-md-12">
        			<div class="title">微信红包群</div>
        			<div class="desc">想要快速出单加我，人脉都是对你产品感兴趣的精准客户，不是软件加粉，人工筛选导入，都是根据亲做的产品筛选对你产品感兴趣和有意向购买的精准客户，保证没有微商，只有对你产品感兴趣的客源才能让你出单多多</div>
        			<div class="content">
                        sfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfdssfsdfdsfdsfdsfdsfds
                    </div>
        		</div>
        	</div>
		</div>
		<div class="col-lg-3">
			<div class="info_fr ml20">
                <ul>
                    
                    <li class="ellips weixinqunICON">
                        <a href="/article?id=869580">
                            因喉咙发炎无法唱下去，华仔忍痛取消演唱会！
                        </a>
                    </li>
                    
                    <li class="ellips weixinqunICON">
                        <a href="/article?id=869579">
                            在每个人的生命历程中总会遇到很多人，人生的际遇并非寻常
                        </a>
                    </li>
                    
                    <li class="ellips weixinqunICON">
                        <a href="/article?id=869578">
                            不去提升自己，那么换来的可能是男人的背叛！
                        </a>
                    </li>
                    
                    
                </ul>
            </div>
		</div>
	</div>
</div>