<div class="layui-col-md12" style="height:40px;line-height:40px;">
    <span class="layui-breadcrumb" style="visibility: visible;">
      <a>位置：</a>
      <a href="/">首页</a>
      <span lay-separator="">/</span>
      <a>微信群</a>
      <span lay-separator="">/</span>
      <a><cite>详情</cite></a>
    </span>
</div>
<div class="c-body layui-col-md12 wxq-detail">
	<div class="layui-row">
		<div class="layui-col-lg12">
    		<div class="layui-row">
        		<div class="layui-col-md4" style="text-align:center;">
        			<div class="wxq-code">
            			<div class="layui-tab">
                          <ul class="layui-tab-title">
                            <li class="layui-this">群二维码</li>
                            <li>群主微信</li>
                          </ul>
                          <div class="layui-tab-content">
                          	<div class="layui-tab-item layui-show"><img src="<?=$info['code']?>" width="200"></div>
                          	<div class="layui-tab-item"><img src="<?=$info['qz_code']?>" width="200"></div>
                          	<div class="p1"><p class="t_txt">微信扫一扫，添加关注</p></div>
                          </div>
                        </div>
        			</div>
        		</div>
        		<div class="layui-col-md8 content">
        			<div class="title"><?=$info['name']?></div>
        			<div class="desc">简介：<?=$info['desc']?></div>
        			<div class="other-info">
                        <ul>
                            <li class="layui-col-xs4"><span>行业</span><a href="<?=$this->url->get('wx/list',['categoryId'=>$info['category_id']])?>"><?=$categoryPairs[$info['category_id']]?></a></li>
                            <li class="layui-col-xs4"><span>查看</span><?=$info['pv']?> 次</li>
                            <li class="layui-col-xs4"><span>时间</span><?=$info['create_time']?></li>
                            <!-- <li style="width:100%"><span>标签：</span></li> -->
                        </ul>
                    </div>
        		</div>
        	</div>
		</div>
	</div>
</div>
<script>
$(function(){
	layui.use('element', function(){
		  var element = layui.element;
		  
		  //…
		});
});
</script>