<div class="layui-col-md12" style="height:40px;line-height:40px;">
    <span class="layui-breadcrumb" style="visibility: visible;">
      <a>位置：</a>
      <a href="/">首页</a>
      <span lay-separator="">/</span>
      <a>会员中心</a>
      <span lay-separator="">/</span>
      <a><cite>微信群列表</cite></a>
    </span>
</div>
<div class="c-body layui-col-md12">
	<div class="layui-row">
		<div class="layui-col-md3">
			<ul class="layui-nav layui-nav-tree layui-bg-cyan" style="width:auto;" id="L_demoNav" lay-filter="test">
                <li class="layui-nav-item layui-nav-itemed">
                  <a href="javascript:;">会员中心</a>
                  <dl class="layui-nav-child">
                    <dd><a href="javascript:;" class="layui-this">微信群列表</a></dd>
                    <dd><a href="<?=$this->url->get('member/addWxGroup');?>">发布微信群</a></dd>
                  </dl>
                </li>
              <span class="layui-nav-bar" style="top: 322.5px; height: 0px; opacity: 0;"></span></ul>
		</div>
		<div class="layui-col-md9">
    		<div class="layui-row">
          <div class="layui-card-header" style="padding: 0;margin:0 15px;">微信群列表</div>
          <div class="layui-card-body">
            <table class="layui-table">
              <colgroup>
                <col width="150">
                <col width="200">
                <col>
              </colgroup>
              <thead>
                <tr>
                  <th>微信群名称</th>
                  <th>群主微信号</th>
                  <th>简介</th>
                  <th>状态</th>
                  <th>操作</th>
                </tr> 
              </thead>
              <tbody>
              <?php if(!empty($data['list'])):
                        foreach ($data['list'] as $val):
              ?>
                <tr>
                  <td><?=$val['name']?></td>
                  <td><?=$val['qz_number']?></td>
                  <td><?=$val['desc']?></td>
                  <td><?php switch ($val['deleted']):case 0:echo '审核成功';break;case 1:echo '审核中';break;case 2:echo '删除';break;case 3:echo '审核失败';break;endswitch;?></td>
                  <td><a href="<?=$this->url->get('member/editWxGroup', ['id'=>$val['id']])?>">编辑</a> | <a href="<?=$this->url->get('member/delWxGroup', ['id'=>$val['id']])?>">删除</a></td>
                </tr>
               <?php endforeach;else :?>
                <tr>
                  <td colspan="5">暂无数据。。。</td>
                </tr>
              <?php endif;?>
              </tbody>
            </table>
            <div id="page"></div>
            </div>
            </div>
            </div>
          </div>
        </div>
		</div>
	</div>
</div>
<script>
$(function(){
	//注意：导航 依赖 element 模块，否则无法进行功能性操作
	layui.use('element', function(){
	  var element = layui.element;
	  
	  //…
	});
	layui.use('laypage', function(){
		  var laypage = layui.laypage;
		  
		  //执行一个laypage实例
		  laypage.render({
		    elem: 'page' //注意，这里的 test1 是 ID，不用加 # 号
		    ,count: <?=$data['pageinfo']['total']?>, //数据总数，从服务端得到
		  limit:20,
		  });
		});
	layui.use('layer', function(){
		var layer = layui.layer;
		<?php if($errorMsg):?>
		layer.msg('<?=$errorMsg?>', {icon:5});
		<?php endif;?>
		<?php if($successMsg):?>
		layer.msg('<?=$successMsg?>', {icon:6});
		<?php endif;?>
	});
});
</script>