<div class="layui-col-md12" style="height:40px;line-height:40px;">
    <span class="layui-breadcrumb" style="visibility: visible;">
      <a>位置：</a>
      <a href="/">首页</a>
      <span lay-separator="">/</span>
      <a>会员中心</a>
      <span lay-separator="">/</span>
      <a><cite>微信群列表</cite></a>
    </span>
</div>
<div class="c-body layui-col-md12">
	<div class="layui-row">
		<div class="layui-col-md3">
			<ul class="layui-nav layui-nav-tree layui-bg-cyan" style="width:auto;" id="L_demoNav" lay-filter="test">
                <li class="layui-nav-item layui-nav-itemed">
                  <a href="javascript:;">会员中心</a>
                  <dl class="layui-nav-child">
                    <dd><a href="javascript:;" class="layui-this">微信群列表</a></dd>
                    <dd><a href="<?=$this->url->get('member/addWxGroup');?>">发布微信群</a></dd>
                  </dl>
                </li>
              <span class="layui-nav-bar" style="top: 322.5px; height: 0px; opacity: 0;"></span></ul>
		</div>
		<div class="layui-col-md9">
    		<div class="layui-row">
          <div class="layui-card-header" style="padding: 0;margin:0 15px;">简单用法</div>
          <div class="layui-card-body">
            <table class="layui-table">
              <colgroup>
                <col width="150">
                <col width="200">
                <col>
              </colgroup>
              <thead>
                <tr>
                  <th>昵称</th>
                  <th>加入时间</th>
                  <th>签名</th>
                </tr> 
              </thead>
              <tbody>
                <tr>
                  <td>贤心</td>
                  <td>2016-11-29</td>
                  <td>人生就像是一场修行</td>
                </tr>
                <tr>
                  <td>许闲心</td>
                  <td>2016-11-28</td>
                  <td>于千万人之中遇见你所遇见的人，于千万年之中，时间的无涯的荒野里…</td>
                </tr>
              </tbody>
            </table>
            </div></div>
            </div>
          </div>
        </div>
		</div>
	</div>
</div>
<script>
$(function(){
	//注意：导航 依赖 element 模块，否则无法进行功能性操作
	layui.use('element', function(){
	  var element = layui.element;
	  
	  //…
	});
});
</script>